### ISSUE TITLE
Make future proof for Ember 1.13 / 2.0

### ISSUE THREAD

**Issue by temo44** [yahoo/ember-intl#131]
I've updated Ember to 1.12 recently and started getting these deprecation warnings:

DEPRECATION: `lookup` was called on a Registry. The `initializer` API no longer receives a container, and you should use an `instanceInitializer` to look up objects from the container. See http://emberjs.com/guides/deprecations#toc_deprecate-access-to-instances-in-initializers for more details.
        at Object.Registry.lookup (http://localhost:4200/assets/vendor.js:12168:26)
        at registerIntl (http://localhost:4200/assets/test.js:1678:51)
        at Object.initialize (http://localhost:4200/assets/test.js:1695:13)
        at http://localhost:4200/assets/vendor.js:14652:23
        at http://localhost:4200/assets/vendor.js:14675:9
        at visit (http://localhost:4200/assets/vendor.js:12696:7)
        at DAG.topsort (http://localhost:4200/assets/vendor.js:12808:11)
        at Namespace.default.extend._runInitializer (http://localhost:4200/assets/vendor.js:14674:13)
        at Namespace.default.extend.runInitializers (http://localhost:4200/assets/vendor.js:14648:12)

Perhaps this can be resolved?

**Comment by temo44** [comment]
I just realized this issue is kinda stupid, as you guys have a nice 'road to 2.0.0' thing going on :). My big apologies. 

{{format-number}} broke my application in Ember 1.13, that's why I thought at first it had nothing to do with 2.0.
