### ISSUE TITLE
[Beta] Cannot read property 'rebuild' of undefined

### ISSUE THREAD

**Issue by jcope2013** [yahoo/ember-intl#136]
on ember-intl 2.0.0-beta.3 with ember cli 0.2.7 

```
Cannot read property 'rebuild' of undefined
TypeError: Cannot read property 'rebuild' of undefined
    at Builder.wrapIfNecessary (/Users/joshuacope/my-new-app/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:136:18)
    at readAndReturnNodeFor (/Users/joshuacope/my-new-app/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:44:17)
    at /Users/joshuacope/my-new-app/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:92:24
    at lib$rsvp$$internal$$tryCatch (/Users/joshuacope/my-new-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/joshuacope/my-new-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at /Users/joshuacope/my-new-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1095:13
    at lib$rsvp$asap$$flush (/Users/joshuacope/my-new-app/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)
```

**Comment by jasonmit** [comment]
It's very difficult to track betas while maintaining some level of support for the latest stables.  So with that, I haven't attempted to support 2.0 yet.

I will investigate though what it will take to fix this though and perhaps get ember 2.0 supported.

**Comment by jcope2013** [comment]
@jasonmit to clarify this on ember 1.13.2 and ember cli 0.2.7, i believe this was an issue in ember cli 0.2.6 that got fixed in 0.2.7 (https://github.com/Gaurav0/ember-cli-jquery-ui/issues/10) but i have a feeling the way the dependency's are loading is causing the issue, it seemed to be this change that is the culprit, doesnt happen on beta 2 (https://github.com/yahoo/ember-intl/commit/460bc9758a2d938cde3bc41c0cc6bfca872bb733), the ember-new-computed has a version of ember-cli 0.2.2 and might be causing the issue

**Comment by jasonmit** [comment]
https://github.com/yahoo/ember-intl/commit/8d9931765d6635d27f489681868b47c3c7066f37 should fix this.  I'll release beta.4 shortly

**Comment by jasonmit** [comment]
Also, unrelated to this issue but worth mentioning.. all of the polyfill filenames are now lowercase.  It's documented, but you might have missed it.

`Intl.complete.js` -> `intl.complete.js`
`en-US` -> `en-us`

**Comment by jcope2013** [comment]
@jasonmit thanks
