### ISSUE TITLE
TypeError: Cannot read property 'format' of undefined on beta 12

### ISSUE THREAD

**Issue by jcope2013** [yahoo/ember-intl#166]
code looks like this, worked on beta 9 fine

```
var msg = intl.findTranslationByKey('userNotification.message.newMessage.message');
var message = intl.formatMessage(msg.content, {name: 'test'});
```

```
Ember.onerror stack: TypeError: Cannot read property 'format' of undefined
    at format (http://localhost:4200/provider/assets/vendor.js:147088:25)
    at null.formatMessage (http://localhost:4200/provider/assets/vendor.js:147590:30)
    at http://localhost:4200/provider/assets/inbox-dashboard.js:13840:30
    at tryCatch (http://localhost:4200/provider/assets/vendor.js:66919:14)
    at invokeCallback (http://localhost:4200/provider/assets/vendor.js:66934:15)
    at publish (http://localhost:4200/provider/assets/vendor.js:66902:9)
    at http://localhost:4200/provider/assets/vendor.js:43743:7
    at Queue.invokeWithOnError (http://localhost:4200/provider/assets/vendor.js:12927:18)
    at Object.Queue.flush (http://localhost:4200/provider/assets/vendor.js:12982:11)
    at Object.DeferredActionQueues.flush (http://localhost:4200/provider/assets/vendor.js:12782:17)
```

**Comment by al3x-edge** [comment]
@jcope2013 `at null.formatMessage (http://localhost:4200/provider/assets/vendor.js:147590:30)` make it look like `intl` is null.

Generally would look something like below for us without variable assignment:
```
this.get('intl').findTranslationByKey()
```

**Comment by al3x-edge** [comment]
@jcope2013 Previous suggestion I thought worked for us, but didn't.  Little poking around, it looks like just `msg` instead of `msg.content`?

![image](https://cloud.githubusercontent.com/assets/62131/8659541/a27fb166-2979-11e5-82cc-b5e1fc8b67bc.png)

**Comment by jasonmit** [comment]
```
var msg = intl.findTranslationByKey('userNotification.message.newMessage.message');
var message = intl.formatMessage(msg.translation, {name: 'test'});
```

Should do the trick and sorry about that.

Just a heads up,`findTranslationByKey` will soon return just the translation string and not an object.

**Comment by jcope2013** [comment]
thanks
