### ISSUE TITLE
`ember help generate` fails when ember-intl is installed

### ISSUE THREAD

**Issue by EndangeredMassa** [yahoo/ember-intl#225]
When using `ember help generate`, ember-intl fails to report its generators with the following error.

```
Cannot find module '../../lib/locale-writer'
Error: Cannot find module '../../lib/locale-writer'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/sean/source/influencer-search/node_modules/ember-intl/blueprints/translation/index.js:6:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by jasonmit** [comment]
Fixing now, thanks for reporting

**Comment by jasonmit** [comment]
2.0.0-beta.23 fixes this
